name: Test
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Configure Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: Unit tests
      run: make test
